ARCHS = arm64 arm64e
DEBUG = 0
FINALPACKAGE = 1
FOR_RELEASE = 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = HamadShield
HamadShield_FILES = Tweak.xm
HamadShield_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
